//test case for exception being caught
public class ThrowException
{
    public void someFun()
    {
        throw new Exception();
    }
}